### ISSUE TITLE
Crash when moving into moat

### ISSUE THREAD

**Issue by gregorp** [copperwater/xNetHack#10]
I was playing on Hardfought (xNetHack version 5.1). Wanted to dilute some potions, so I jumped in the moat on the Oracle level. Did it 2 or 3 times, and the game crashed. When I opened the game, it told my I had a game in progress, asked I wanted to abandon it. Got in touch with an admin who recovered the save file. I went back to the Oracle level and jumped in the water again, game crashed again, no "game in progress" notification this time.

When I moved into the moat I was a Samurai, Level 10, ~90 HP, wearing GDSM, wielding Snickersnee, and carrying ~8 potions (a couple of which were acid), nothing else in inventory.

Happy to provide additional info or attempt to reproduce if that would help.

**Comment by copperwater** [comment]
Fixed in d820b669b. Not sure why you were trying to get acid potions to dilute anyway, but thanks for the extra context, it helped me make sense of an earlier bug report I couldn't figure out.

**Comment by gregorp** [comment]
Forgetting that acid doesn't dilute :(

Thank you, really enjoying my recent switch to xNetHack!
