### ISSUE TITLE
Impossible with overflowing fountain in big room: "deleting trap (5) containing ammo (218)?"

### ISSUE THREAD

**Issue by tux3** [copperwater/xNetHack#110]
I was on my way to make more holy water, I dipped into the big room's fountain and received the following messages:

```
Your potion of confusion dilutes.  deleting trap (5) containing ammo (218)?
Program in disorder!  (Saving and reloading may fix this problem.)
Please report these messages to aosdict@gmail.com.
Alternatively, contact local support: Contact K2 or Tangles on
irc.libera.chat channel #hardfought
Water gushes forth from the overflowing fountain!
```

The room looks like this:

![snap-1215](https://github.com/copperwater/xNetHack/assets/5155966/ead057dd-4be2-40da-9330-4f983c527d40)

**Comment by copperwater** [comment]
This should now be fixed by https://github.com/copperwater/xNetHack/commit/598164dead1480c14a2b6860eb5dfc27717c068f.
