### ISSUE TITLE
Boulder...

### ISSUE THREAD

**Issue by every-in-austin** [copperwater/xNetHack#111]
Stood on the upstairs on the nemesis level of the ranger quest and read a cursed scroll of  earth. The scroll disappeared but no boulder was produced. Some new bit of f*ckery?

**Comment by copperwater** [comment]
The logical condition was flipped so that earth scrolls worked only on outdoors levels, instead of non-outdoors levels. This is fixed by https://github.com/copperwater/xNetHack/commit/ed0d51feab7ddf42239c334af51abb4c5b06dc0d.
