### ISSUE TITLE
Disable "A - Auto-select everything" menu item when putting things into a container

### ISSUE THREAD

**Issue by copperwater** [copperwater/xNetHack#124]
Basically, this leads to bohsplosions, and actual cases where the player wants to put everything they can into a container are expected to be very rare (and can be worked around with a few key presses anyway). 

There is supposedly an UnNetHack commit which does this.

**Comment by entrez** [comment]
I mentioned this on IRC at some point but I want to point out that I actually use A for putting things into bags a lot now that it actually works in combination with other filters.

Maybe this is moot anyway now that there's an upstream commit to add paranoid 'A', but I think it might be cool to require an additional filter on top of 'A', taking the 3.7 filter behavior from optional to required -- that would allow you to use 'AP' to drop a pile of items you just picked up into your bag, or 'A)' transfer an entire class of items from one bag to another easily, but it would prevent a typo of 'A' alone from socking everything in your inventory away.  'Aa' would continue to product the existing 'A' behavior, but it requires two keys so would hopefully be less likely to typo.

**Comment by copperwater** [comment]
OK, let's hold off on this for now until we see how paranoid A works in vanilla.

**Comment by copperwater** [comment]
Withdrawing this. Paranoid A behavior in vanilla seems to work well enough. (It is not in current xNetHack development, but will get added in the next vanilla merge.)
