### ISSUE TITLE
Magic fountains can give a "healing spring" effect when quaffed

### ISSUE THREAD

**Issue by copperwater** [copperwater/xNetHack#128]
If quaffing from a magic fountain AND you hit the random chance that normally gives you a gain ability effect AND either Pw or HP is below 60%, restore both to max and add 1 point to the max of each. The fountain then becomes nonmagic.

**Comment by zindorsky** [comment]
Question: Would this be in addition to the gain ability effect, or in place of it?

**Comment by copperwater** [comment]
Intent is that it would replace the gain ability effect.

**Comment by copperwater** [comment]
Merged in.
