### ISSUE TITLE
Game crash after fire trap causes multiple potions to explode

### ISSUE THREAD

**Issue by gregorp** [copperwater/xNetHack#13]
Hi there, just had a game crash (playing on Hardfought, xNetHack 5.1) after I stepped on a fire trap. I got the "flames erupt from the floor" message, my shield smouldered, a potion exploded and I healed a little bit - and I was prompted to name that potion, then another potion exploded "strange feeling for a moment, then it passes", I named the second potion, and basically as soon as I hit enter with that name I was back at the Hardfought home screen - no more messages, no dying, etc. Starting up xNetHack again I got the new game screen.

**Comment by copperwater** [comment]
What account do you play under on Hardfought? K2 hasn't found any crash logs or anything to restore. Is it possible you disconnected from the server at that time?

**Comment by gregorp** [comment]
Account name is `zoya`.

It didn't seem like a disconnection - I'm playing on Windows using PuTTY, and when I disconnect usually there's a error message and I have to reconnect, and the game is recovered. With this, there was no reconnection, no need to log in again, I was just at the Hardfought play selection menu. 

Since it was potions exploding, it seemed similar to #10, not sure if there's anything to that.

**Comment by copperwater** [comment]
K2 discovered an emergency save which was playable, but I loaded it and didn't find anything broken when repeatedly stepping on the magic trap. The paniclog contained an 'extract_nobj: object lost' panic, but I don't know if this was related to your game. If it was, it could be related to the trap ammo code, which contains some extract_nobj calls, but I don't see how that would happen as magic traps don't have ammo, and the trap wasn't being destroyed. For now I don't have enough information to figure it out.

Shouldn't be related to #10 as that specifically dealt with wetting items and the acid-water interaction; there's no general exploding potion code.

If you tell K2 you want your game recovered while you don't have some other game in progress, he'll recover it for you.

**Comment by gregorp** [comment]
Thanks, I appreciate the investigation! I've got another game going now, so I'll just chalk that up to a strange YASD :)
