### ISSUE TITLE
Use pets' correct gendered pronoun (not "it") in messages

### ISSUE THREAD

**Issue by copperwater** [copperwater/xNetHack#144]
At least for domestic pets that can be starters. Enumerating all the monster species for which gendered pronouns are relevant may be too big of a task. 

This is probably an additional condition which should slot into pronoun_gender().

**Comment by entrez** [comment]
I don't know if I like the idea that taming or untaming an arbitrary monster should change how the game refers to it.  I think I understand the motivation (that many people refer to their pet dogs or cats as "he" or "she" in the modern day) but I don't know if I agree that is worth introducing these inconsistencies and weird implications like "once a pet becomes untame, you forget its sex".
