### ISSUE TITLE
Vary the legacy start-of-game text based on role

### ISSUE THREAD

**Issue by copperwater** [copperwater/xNetHack#147]
YANI #1156: The game opening text for certain roles is changed from "It is written in the Book of [deity]:"
  - Caveman: "It is painted in the Sacred Caves of [deity]"
  - Valkyrie: "It is sung in the Sagas of [deity]"
  - Wizard: "It is inscribed in the Tomes of [deity]"
  - Barbarian: "It is etched on the Stone Tablets of [deity]"
  - Archeologist: "It is written in the ancient Scrolls of [deity]"
  - Priest: "It is taught in the Temple of [deity]"
  - Monk: "It is chanted in the Rites of [deity]"
  - Samurai: "It is illustrated in the Emakimono of [deity]"
  - will require a bit of lua finagling to make work, because normally this is just a constant com_pager call. maybe it can be a function, or use a new % conversion specifier.

This doesn't involve changing the following text describing Moloch taking the Amulet to Gehennom or your god wanting it back so they send you on the quest.

Roles that have not yet had a unique text brainstormed:
- Healer
- Ranger
- Rogue
- Tourist
- Knight

**Comment by zindorsky** [comment]
Some suggestions:

* Rogue: "It is scrawled in the graffiti under the temple of [deity]"
* Tourist: "It is referenced in the footnotes of [deity]'s guide to Ankh-Morpork"
