### ISSUE TITLE
unable to interact with objects on the ground when using the option "force_invmenu"

### ISSUE THREAD

**Issue by voguelike** [copperwater/xNetHack#15]
for example, you can't eat a corpse or food without picking it up, and it's completely impossible to quaff from fountains.

normally the game prompts you asking if you want to eat the corpse below you or quaff from the fountain if you are standing on it, and if you say no then it moves on to your inventory but this behaviour is absent in xnethack and without the ability to specify the ground from the inventory menu, there's no way to interact with things on the ground with this option enabled.

this happens both in the current master as well as the current xnethack version on hardfought.

**Comment by voguelike** [comment]
just noticed that this also happens when trying to apply wands to break them. the menu that pops up doesn't include wands by default and is missing the option to list everything in your inventory.

**Comment by copperwater** [comment]
I'm pretty sure at this point that I'm going to roll back the getobj patch, so this will hopefully go away when that happens.

**Comment by copperwater** [comment]
The future of the getobj patch is here! https://github.com/NetHack/NetHack/pull/438

**Comment by copperwater** [comment]
Should be "fixed" now, in that floor items aren't selectable anymore in getobj prompts, so there shouldn't be an expectation that they appear in force_invmenu.
