### ISSUE TITLE
Vault Guards

### ISSUE THREAD

**Issue by every-in-austin** [copperwater/xNetHack#197]
On three separate instances in the new release a vault guard has left me at a location with no exit. Once against a blank wall of a shop, once behind an iron grate and recently on an unexplored dead end corridor blocked by boulders. Since all of these could have been addressed with either digging or teleport I have to wonder if this is by design...

**Comment by entrez** [comment]
I feel pretty confident it's not by design, that sounds very rude of them

**Comment by entrez** [comment]
I think a dead end of a corridor with boulders and behind an iron grate sound like they could conceivably be normal (but unlucky) outcomes of the guard corridor but "against the blank wall of a shop" sounds strange.  There was no corridor there?

**Comment by every-in-austin** [comment]
In all three instances I started with automatic searching (Ranger) and there were no doors or corridors to be found. Perhaps something crept in from EvilHack... =)

**Comment by entrez** [comment]
Were you left standing on a solitary corridor space when the vault guard disappeared in the "shop wall" case?  Or were you left encased in stone?

**Comment by entrez** [comment]
The destination of the path should always be a corridor space (the closest corridor space to the vault basically) but I don't think the algorithm takes into account that some corridor spaces could be isolated niches that have no escape.  That's vanilla behavior though afaict.  I'm not sure about the isolated niche next to a blank shop wall (if that's what it was and you weren't left encased in stone) but maybe that does happen and I've just never noticed it, probably merits more investigation.

**Comment by every-in-austin** [comment]
I couldn't move so I'm unsure if there was a # beneath my feet or not. The net result was the same...

**Comment by every-in-austin** [comment]
I know when using magic mapping I have occasionally seen one square "closets" with no door, obvious or hidden. Perhaps that can also happen with stores...

**Comment by copperwater** [comment]
I think isolated niches next to a shop are possible, if they generate without iron bars or doors (the algorithm for selecting a shop just checks that it has exactly 1 door, not also that it has no closets. Actually I think shops with an iron bar closet might be possible.) so if entrez is correct about the vault guard leading you to a corridor without concern for that corridor being connected to anything, this is possible. However, no-door closets and iron bar closets should always generate with a scroll of teleportation for anyone who finds themselves trapped there.

**Comment by every-in-austin** [comment]
Scroll, wand or pickaxe, preferably not cursed...

**Comment by copperwater** [comment]
@every-in-austin I don't currently have enough info to take any action on this issue.

If this happens again, can you please record:
- If there's a scroll of teleportation on the space you're left in
- Whether you're on a corridor or embedded in rock after the guard and corridor disappear (check with #terrain) 
- What the map looks like (screenshot or text cut and paste) OR ideally, save the game and have K2 make a copy of the save file for me to look at if this is a Hardfought game.
