### ISSUE TITLE
while helplessstuck

### ISSUE THREAD

**Issue by vultur-cadens** [copperwater/xNetHack#200]
There was a death reported in the #hardfought channel [recently](https://hardfought.org/irclog/%23hardfought-2023-09-25.log):

`<+Beholder> [hdf-us] [xnh] Gouhan (Sam Hum Mal Law), 82677 points, T:29051, killed by a residual undead turning effect, while helplessstuck in human zombie form`

This is not visible in the [dumplog](https://www.hardfought.org/userdata/G/Gouhan/xnethack/dumplog/1695557525.xnh.txt), but xlogfile contains `while=helplessstuck in human zombie form`

This can be reproduced by being permanently zombified, then praying to a lawful god to get killed.  (I disabled [the part of the code](https://github.com/copperwater/xNetHack/blob/18fcd3a660549e406d7b72c0b4a83e3d53276218/src/topten.c#L789) that skips the score list to get it to save an xlogfile entry in wizard mode.)

https://github.com/copperwater/xNetHack/blob/18fcd3a660549e406d7b72c0b4a83e3d53276218/src/topten.c#L363-L372

It looks like this is due to `helpless` always being set to "helpless" even if `gm.multi` is 0, causing `and` to be set to the empty string.  To fix it, `helpless` should probably be set to the empty string if `gm.multi` is 0.

**Comment by entrez** [comment]
I've had a PR to address this open for a while, it's just waiting for @copperwater to get around to it (#189).

**Comment by entrez** [comment]
This should now be fixed as of 1f7f315.
