### ISSUE TITLE
Slings

### ISSUE THREAD

**Issue by every-in-austin** [copperwater/xNetHack#211]
What is the effect (if any) of enchanting the now "extension of a throwing motion" sling in xnh?

**Comment by copperwater** [comment]
Can you clarify what you mean? Using t to throw objects from a sling while wielding it instead of f to fire quivered ammo is not any different.

I don't recall ever changing the rules on enchantment of a sling - like other launchers, it should affect accuracy but not damage.

**Comment by every-in-austin** [comment]
Since it is, as far as I know, the only launcher that transfers strength to damage, I was a bit puzzled. But if enchantment simply improves the to_hit that is good as well. Perhaps that will make it a semi-viable unskilled ranged weapon for monks...

**Comment by copperwater** [comment]
Question answered, seems like.
