### ISSUE TITLE
Allow for easy Lua unbundling

### ISSUE THREAD

**Issue by clausecker** [copperwater/xNetHack#37]
Good evening!  I'm trying to make a FreeBSD package out of this and the way you use Lua is quite weird.  Please add a simple way to use the system's Lua installation instead.  Also let me know if a specific Lua version is needed.

**Comment by copperwater** [comment]
xNetHack doesn't change the way lua is used, it's the same as vanilla, so I would say taking this up with the vanilla devteam would be the way to go. It's not a priority for me to try unraveling NetHack's confusing lua build process.
