### ISSUE TITLE
Curses windowport overwrites terminal color settings

### ISSUE THREAD

**Issue by Terrarian51** [copperwater/xNetHack#42]
I'm that guy who first prompted [that issue](https://www.reddit.com/r/nethack/comments/nmmymo/xnethack_curses_interface_overwrites_the_colors/) on Reddit. So I would like to repost it here.  

Hi, guys! I'm still trying to play xNetHack, but I have no knowledge about coding. However, now I've noticed, that this fork, xNetHack, forcefully overwrites my colors for curses interface, and I don't know, how could I change that behaviour. The set of color options from configuration file doesn't work. What should I do to set my preset of colors, taken from windows prompt?

Here is the link to the same issue in NetHack branch, with some nice info provided by entrez: [Curses windowport overwrites terminal color settings](https://github.com/NetHack/NetHack/issues/522#issue-904537815)

**Comment by copperwater** [comment]
Closing in favor of https://github.com/NetHack/NetHack/issues/522; there is no plan to do this in xNetHack independently of vanilla.
