### ISSUE TITLE
Floating dragon scales

### ISSUE THREAD

**Issue by gregorp** [copperwater/xNetHack#67]
I'm on Vlad's Tower, Level 1, and killed a Gray Dragon on an "air" tile while levitating via a ring. I got a message about it's body falling away and disappearing, but it also dropped dragon scales that are just "floating" there in the air. Seems like a bug that the scales don't also fall away.

Playing on Hardfought. 
Unix NetHack Version 7.0.0 - last build Mar 20 2022 21:41:19
(d8d347d964b310a1d65c52326b9d30ac073ddabd).

Thanks for all your work!

**Comment by entrez** [comment]
`mksobj_at` doesn't call `flooreffects` before placing the object onto the map (and most of its callers can't handle it failing to create an object, so adding a `flooreffects` call in there isn't exactly a simple solution either).  This is what's used for creating dragon scales after a dragon dies.  Other things have similar problems, e.g. stoning a monster over the chasm leaves a floating statue.

I'm not sure what the right solution is... could use something other than `mksobj_at` for these scenarios, but I suspect it'll be a lot of work tracking down all the places it's used directly and indirectly.

It's the same story with `mkobj_at`, too, though I don't know if there are any cases where that can be called over a chasm.

**Comment by copperwater** [comment]
This has been fixed for a while now in bfd419f.
