### ISSUE TITLE
Game-ending crash when viewing encyclopedia entry for 'dart' or 'shuriken'

### ISSUE THREAD

**Issue by Ardub23** [copperwater/xNetHack#7]
In xNetHack version 5.0 on hardfought.org (US server), attempting to view the encyclopedia and additional information on darts or shuriken crashes to the server menu. Upon re-entering the game, I'm told "There is already a game in progress under your name.  Destroy old game?" Answering 'no' boots me back to the server menu again.

This happens when inspecting darts or shuriken from the inventory, or when using `/` (what is) followed by `?` (something else) and typing "dart" or "shuriken". Typing "darts" or "shurikens" shows the encyclopedia entry, but without the added information (damage, material, etc), and in the case of "darts", the entry is shown twice in a row (which may be unrelated).

I suspect that the error has to do with the bit in the extra information that displays the associated skill. The only weapon I found to show the description "Thrown missile" is the boomerang, which is incorrectly described as using the broadsword skill. SpliceHack doesn't show the weapon's skill, and the bug is absent there.

**Comment by k21971** [comment]
Backtrace of Ardub23's crash - https://termbin.com/1jgg

**Comment by copperwater** [comment]
Hi Ardub, nice to finally talk directly to you :-)

Fixed in 44096d0 in what will become version 5.1.
