### ISSUE TITLE
Can't find object "loadstone" error - Mine's End

### ISSUE THREAD

**Issue by KongMD-Steam** [copperwater/xNetHack#8]
After hitting > to travel down into the Mine's End level, I received this error:

![Screenshot - 4_14_2020 , 6_01_25 PM+1](https://user-images.githubusercontent.com/36478131/79278813-08736680-7e9c-11ea-9774-298e7daa1259.png)

After hitting Enter on that screen, I received this error:
![Screenshot - 4_14_2020 , 6_07_11 PM+1](https://user-images.githubusercontent.com/36478131/79279014-98b1ab80-7e9c-11ea-993b-586ba8ea1528.png)

This was my first time going down this stair. I'm playing an Elven Ranger on hardfought. The server is running xNethack version 5.1. Saving and reloading the game did not cause any errors to occur.

**Comment by copperwater** [comment]
Great bug report! This should be fixed in 87197da.
