### ISSUE TITLE
Jumping boots messaging

### ISSUE THREAD

**Issue by every-in-austin** [copperwater/xNetHack#87]
I'm pretty sure my legs should feel shorter when I take my jumping boots off...

**Comment by entrez** [comment]
You can take advantage of it by putting on and taking off your boots repeatedly, to get a job as a stilt walker without any of the expense of buying stilts.

**Comment by every-in-austin** [comment]
I'll probably have to ditch my elven helm for something harder once I start banging into the dungeon ceiling...
